### ISSUE TITLE
Fatal error on init-recipe

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector-generator#39]
on PHP 8.2

1. Create an empty directory
2. `composer require rector/rector-generator rector/rector`
3. `vendor/bin/rector init-recipe`

```
  - Locking nette/utils (v3.2.10)
  - Locking nikic/php-parser (v4.17.1)
  - Locking phpstan/phpstan (1.10.29)
  - Locking psr/container (2.0.2)
  - Locking rector/rector (0.18.0) 👈🏻
  - Locking rector/rector-generator (0.7.3) 👈🏻
  - Locking sebastian/diff (5.0.3)
  - Locking symfony/config (v6.3.2)
  - Locking symfony/console (v6.3.2)
  - Locking symfony/dependency-injection (v6.1.12)
  - Locking symfony/deprecation-contracts (v3.3.0)
  - Locking symfony/filesystem (v6.3.1)
  - Locking symfony/finder (v6.3.3)
  - Locking symfony/polyfill-ctype (v1.27.0)
  - Locking symfony/polyfill-intl-grapheme (v1.27.0)
  - Locking symfony/polyfill-intl-normalizer (v1.27.0)
  - Locking symfony/polyfill-mbstring (v1.27.0)
  - Locking symfony/service-contracts (v3.3.0)
  - Locking symfony/string (v6.3.2)
  - Locking symplify/package-builder (11.3.0)
  - Locking webmozart/assert (1.11.0)
```

```
PHP Fatal error:  Uncaught RectorPrefix202308\Illuminate\Contracts\Container\BindingResolutionException:
 Target [Symfony\Component\Console\Input\InputInterface] is not instantiable while building [Rector\Core\Console\ConsoleApplication, Rector\RectorGenerator\Command\InitRecipeCommand, Rector\RectorGenerator\TemplateInitializer, Symfony\Component\Console\Style\SymfonyStyle]. in vendor/rector/rector/vendor/illuminate/container/Container.php:958

Stack trace:
#0 vendor/rector/rector/vendor/illuminate/container/Container.php(796): RectorPrefix202308\Illuminate\Container\Container->notInstantiable()
#1 vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202308\Illuminate\Container\Container->build()
#2 vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202308\Illuminate\Container\Container->resolve()
#3 vendor/rector/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202308\Illuminate\Container\Container->make()
#4 vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202308\Illuminate\Container\Container->resolveClass()
#5 vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202308\Illuminate\Container\Container->resolveDependencies()
#6 vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202308\Illuminate\Container\Container->build()
#7 vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202308\Illuminate\Container\Container->resolve()
#8 vendor/rector/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202308\Illuminate\Container\Container->make()
#9 vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202308\Illuminate\Container\Container->resolveClass()
#10 vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202308\Illuminate\Container\Container->resolveDependencies()
#11 vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202308\Illuminate\Container\Container->build()
#12 vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202308\Illuminate\Container\Container->resolve()
#13 vendor/rector/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202308\Illuminate\Container\Container->make()
#14 vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202308\Illuminate\Container\Container->resolveClass()
#15 vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202308\Illuminate\Container\Container->resolveDependencies()
#16 vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202308\Illuminate\Container\Container->build()
#17 vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202308\Illuminate\Container\Container->resolve()
#18 vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202308\Illuminate\Container\Container->make()
#19 [internal function]: RectorPrefix202308\Illuminate\Container\Container->RectorPrefix202308\Illuminate\Container\{closure}()
#20 vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array()
#21 vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202308\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202308\Illuminate\Container\{closure}()
#22 vendor/rector/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202308\Illuminate\Container\Util::unwrapIfClosure()
#23 vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202308\Illuminate\Container\Container->resolvePrimitive()
#24 vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202308\Illuminate\Container\Container->resolveDependencies()
#25 vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202308\Illuminate\Container\Container->build()
#26 vendor/rector/rector/vendor/illuminate/container/Container.php(785): RectorPrefix202308\Illuminate\Container\Container->RectorPrefix202308\Illuminate\Container\{closure}()
#27 vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202308\Illuminate\Container\Container->build()
#28 vendor/rector/rector/vendor/illuminate/container/Container.php(644): RectorPrefix202308\Illuminate\Container\Container->resolve()
#29 vendor/rector/rector/bin/rector.php(131): RectorPrefix202308\Illuminate\Container\Container->get()
#30 vendor/rector/rector/bin/rector(5): require_once('...')
#31 vendor/bin/rector(120): include('...')
#32 {main}
  thrown in vendor/rector/rector/vendor/illuminate/container/Container.php on line 958
```

Please help.

**Comment by TomasVotruba** [comment]
Hi, this package is used only for our internal use, as it require our structure in place.
